import { readFile, writeFile } from "node:fs/promises";
import { promisify } from "node:util";
import Chafa from "chafa-wasm";

const argumentsByName = parseArguments(process.argv.slice(2));
const draigPath = requireArgument(argumentsByName, "draig");
const wordmarkPath = requireArgument(argumentsByName, "wordmark");
const outputPath = argumentsByName.get("output") ?? "src/interaction/generated-brand.ts";

const chafa = await Chafa();
const imageToAnsi = promisify(chafa.imageToAnsi);
const [draigImage, wordmarkImage] = await Promise.all([readFile(draigPath), readFile(wordmarkPath)]);

const variants = {
  widePlain: await createVariant(false, 12, 7),
  wideColor: await createVariant(true, 12, 7),
  compactPlain: await createVariant(false, 7, 5),
  compactColor: await createVariant(true, 7, 5)
};

const generated = `// Generated by tools/brand-art/generate.mjs using chafa-wasm 0.3.3.\n` +
  `// Source artwork: Draig mascot and Draigara lowercase wordmark. Do not edit by hand.\n\n` +
  Object.entries(variants).map(([name, value]) => `export const ${name} = ${JSON.stringify(value)};`).join("\n\n") +
  "\n";

await writeFile(outputPath, generated, "utf8");
console.log(`Generated ${outputPath}`);

async function createVariant(color, draigHeight, wordmarkHeight) {
  const [draig, wordmark] = await Promise.all([
    convert(draigImage, draigHeight, color),
    convert(wordmarkImage, wordmarkHeight, color)
  ]);
  const identity = color
    ? "\u001b[38;2;255;255;255mdraigara\u001b[0m  \u001b[38;2;249;115;22mFORGE\u001b[0m"
    : "draigara  FORGE";
  return joinColumns(draig, [...wordmark, identity]);
}

async function convert(image, height, color) {
  const bytes = image.buffer.slice(image.byteOffset, image.byteOffset + image.byteLength);
  const { ansi } = await imageToAnsi(bytes, {
    format: chafa.ChafaPixelMode.CHAFA_PIXEL_MODE_SYMBOLS.value,
    height,
    fontRatio: 0.5,
    colors: color
      ? chafa.ChafaCanvasMode.CHAFA_CANVAS_MODE_TRUECOLOR.value
      : chafa.ChafaCanvasMode.CHAFA_CANVAS_MODE_FGBG.value,
    colorExtractor: chafa.ChafaColorExtractor.CHAFA_COLOR_EXTRACTOR_AVERAGE.value,
    colorSpace: chafa.ChafaColorSpace.CHAFA_COLOR_SPACE_RGB.value,
    symbols: "block+border+space-wide-inverted",
    fill: "none",
    fg: 0xf97316,
    bg: 0x000713,
    fgOnly: false,
    dither: chafa.ChafaDitherMode.CHAFA_DITHER_MODE_NONE.value,
    ditherGrainWidth: 4,
    ditherGrainHeight: 4,
    ditherIntensity: 1,
    preprocess: true,
    threshold: 0.5,
    optimize: 5,
    work: 5
  });
  return trimEmptyEdges(ansi.replaceAll("\r", "").split("\n"));
}

function joinColumns(left, right) {
  const leftWidth = Math.max(...left.map(visibleWidth));
  const height = Math.max(left.length, right.length);
  const rightOffset = Math.max(0, Math.floor((height - right.length) / 2));
  const lines = [];
  for (let index = 0; index < height; index += 1) {
    const leftLine = left[index] ?? "";
    const rightLine = right[index - rightOffset] ?? "";
    lines.push(`${leftLine}${" ".repeat(leftWidth - visibleWidth(leftLine) + 3)}${rightLine}`.trimEnd());
  }
  return lines.join("\n");
}

function visibleWidth(value) {
  return stripAnsi(value).length;
}

function stripAnsi(value) {
  return value.replace(/\u001b\[[0-9;]*m/g, "");
}

function trimEmptyEdges(lines) {
  while (lines.length > 0 && stripAnsi(lines[0]).trim().length === 0) lines.shift();
  while (lines.length > 0 && stripAnsi(lines.at(-1)).trim().length === 0) lines.pop();
  return lines;
}

function parseArguments(values) {
  const parsed = new Map();
  for (let index = 0; index < values.length; index += 2) {
    const key = values[index];
    const value = values[index + 1];
    if (key?.startsWith("--") !== true || value === undefined) {
      throw new Error("Expected --draig <path> --wordmark <path> [--output <path>].");
    }
    parsed.set(key.slice(2), value);
  }
  return parsed;
}

function requireArgument(argumentsByName, name) {
  const value = argumentsByName.get(name);
  if (value === undefined) throw new Error(`Missing required --${name} path.`);
  return value;
}
